### PR TITLE
Several major improvements

### PR DESCRIPTION
**Pull request by StevePotter**
Hi, I started off with the goal to support multiple Mixpanel destinations, and ended up doing several big improvements to this great package:

1. Multiple Mixpanel destinations.  With the new MixpanelInstance class, you can create mixpanel objects for multiple API tokens.
2. Flow typing.  The javascript was upgraded to use Flow types for a better development experience.
3. Better Android thread safety.  Now there should be no risk of people running into threading or other internal errors when calling track.
4. Backwards compatible API *.  All the original methods are still there with the same signatures.
5. Promises instead of callbacks in the new `MixpanelInstance` class for `getDistinctId` and `getSuperProperty`.  Original APIs with callbacks are still supported.

* Errors will be thrown from methods like `track` if the Mixpanel instance has not been initialized.  To avoid this, `sharedInstanceWithToken` now returns a promise that should be awaited before other methods are called.  Example:
```
await mixpanel.sharedInstanceWithToken('3242sdfasj')
mixpanel.track('opened')
```
or 
```
mixpanel.sharedInstanceWithToken('3242sdfasj').then(() => {
mixpanel.track('opened')
})
```

Although the API is backwards compatible, for the aforementioned reason, this is a breaking change and thus I bumped the major version to 1.0.0.

On the native side, the main change I made was adding an internal dictionary to java and objc that holds instances for their respective API tokens.  Effort was made to ensure no performance impact.  The dictionaries are immutable and locks are only used in `sharedInstanceWithToken`.  

Also, in Java I surrounded mixpanel calls like `mixpanel.track` with a lock after looking through Mixpanel Android docs & source and read that's what they recommend.  

This PR should resolve these open issues:
https://github.com/davodesign84/react-native-mixpanel/issues/122
https://github.com/davodesign84/react-native-mixpanel/issues/57
This also makes https://github.com/davodesign84/react-native-mixpanel/pull/114 unnecessary as I've switch those native methods to use promises.

I have tested it in our app and will continue to test over the next week.  I will not be testing push notifications though as we don't use Mixpanel's notification functionality.

I also need to update the README.  I will update it to use the new `MixpanelInstance` kinda like:
```
// root component
import { MixpanelInstance } from 'react-native-mixpanel'

// in constructor or componentDidMount
this.mixpanel = new MixpanelInstance(YOUR_TOKEN)
await this.mixpanel.initialize() // remember to push async in your function declaration, or use .then instead of await
this.mixpanel.track('my event', { name: 'me' })
this.mixpanel.flush()
```

I would appreciate a thorough review and discussion of this PR.  I would especially be interested in a discussion around the new API available in `MixpanelInstance`.  Like I already combined `track` and `trackWithProperties` into just `track` with an optional `properties` param.  A good thing to consider would be, for sample, renaming `set` to `setUserProperties`.  We have a clean slate here and since the current API is preserved with the default exports, we can tweak `MixpanelInstance` without breaking backward compatibility.

For those wishing to use this now, update your `package.json` like so:
```
"react-native-mixpanel": "github:vydia/react-native-mixpanel#f2a5a9c7bd5e1bcdaf9d969ff4ac733443047c1d",
```

Other things we can do to beef it up would be full JS testing (using Jest I suppose) and export a Jest mock so individual developers don't have to.

@davodesign84 I would be happy to handle the merging and publishing if you want.  I would need to be given npm publish permissions though.

Thanks!

### CODE REVIEW

**Comment by sachingadagi** [comment]
Great work! :D 
Just a query, since you've mentioned  about using _flow_, have you explicitly **not added** it as a devDependency?

**Comment by StevePotter** [comment]
@sachingadagi it's not a dependency at all.  Babel will strip the flow types at runtime so unless I'm mistaken it doesn't hurt to have the Flow annotations.  Am I wrong anyone? @davodesign84 I would be happy to merge and publish this if you can give me npm permissions.  email me if you want to talk more.  Thanks

**Comment by frompton** [comment]
@StevePotter we really need this (multiple mixpanel instances) in a current project, how well tested is the code. Are you running it in production? We're debating using your version, even though it's not merged.

**Comment by StevePotter** [comment]
@frompton yeah we use it in production right now.  It works great.  There was one issue we experienced a few months ago but it has been fixed.

**Comment by andrejunges** [comment]
@davodesign84 any chance of merging this?

**Pull request merged**
