### PR TITLE
Added support for push notifications

### PR DESCRIPTION
**Pull request by skeie**
Added support for:
https://mixpanel.com/help/reference/ios-push-notifications
https://mixpanel.com/help/reference/android-push-notifications

### CODE REVIEW

**Comment by skeie** [comment]
Possible to merge this @davodesign84 ?

**Comment by Kerumen** [comment]
Hello @davodesign84 ??

**Comment by dwilt** [comment]
@skeie can you provide some documentation on how to set up the project on the JS side to capture the push notifications and read their data?

**Comment by Kerumen** [comment]
Indeed @dwilt, it lacks some methods to get it working on the JS side. For instance on iOS we should call `[[UIApplication sharedApplication] registerForRemoteNotifications];` and we can't right now.

**Comment by dwilt** [comment]
@Kerumen Thanks for the reply. So for now then, push notifications can't be used at all with this plugin until more work and documentation is provided, correct?

**Comment by Kerumen** [comment]
Yes. I'm not the original committer tho, I just realize that the work was half done.

**Comment by dwilt** [comment]
For now we could probably just use https://github.com/zo0r/react-native-push-notification on the client side and use Mixpanel for the server-side push notification pushes correct?

**Comment by Kerumen** [comment]
Correct. But, as said before, you can't configure push notifications right now with this library. Hence you must stick with local notifications.

**Comment by dwilt** [comment]
If I used the Mixpanel service to send a push notification and https://github.com/zo0r/react-native-push-notification to listen for push notifications, I shouldn't need this plugin at all correct (for push notifications)?

**Comment by dwilt** [comment]
image

**Comment by Kerumen** [comment]
Oh right you can call `PushNotification.configure()` and in the `onRegister` callback call `initPushHandling` with the token generated. This should work.

**Comment by alberthu16** [comment]
@dwilt @Kerumen have either of you tried the  https://github.com/zo0r/react-native-push-notification workaround?

**Comment by dwilt** [comment]
@alberthu16 I haven't no, but I might be coming to this point soon. I'll try posting any successes I make here.

**Comment by alberthu16** [comment]
@dwilt thanks :) it seems to me that push notifications has been implemented though.. I was running into issues while I was on v0.0.10 of this library, but updating to v0.0.14 seemed to fix it.

**Comment by dwilt** [comment]
@alberthu16 can you share some of the code examples that you have to have gotten push notifications to work with mixpanel? I'd love to see how you did it.

**Comment by alberthu16** [comment]
@dwilt will do once I'm done with the process! Still in the middle of hooking things up.

**Comment by dwilt** [comment]
@alberthu16 Awesome, thanks man.

**Pull request merged**
