### PR TITLE
adopt for React Native 0.40

### PR DESCRIPTION
**Pull request by aksonov**

### CODE REVIEW

**Comment by zoontek** [comment]
@davodesign84 Can you eventually put someone in charge of this kind of small PR / npm releases? Thanks :)

**Comment by alfonsodev** [comment]
@aksonov as this is a breaking change, it would be nice to update the README.md , to state that react-native 0.40 or greater is needed, right ?

**Comment by zoontek** [comment]
Any ETA?

**Comment by mikach** [comment]
+1 pls merge

**Comment by corymsmith** [comment]
@davodesign84 Are you still supporting this lib?

**Comment by kollner** [comment]
+1

**Comment by davodesign84** [comment]
Hi all, apologies for the lack of response but I don't have time to follow this library at the moment.

@zoontek I have asked previously so if anyone wants to help out supporting this it would be highly appreciated!

**Pull request merged**
