### PR TITLE
Add setOnce API to android. Add support for notifications on Android/iOS.

### PR DESCRIPTION
**Pull request by mikelambert**
This should fix https://github.com/davodesign84/react-native-mixpanel/issues/38

### CODE REVIEW

**Comment by mikelambert** [comment]
My branch now has support for push tokens on Android and iOS as well. Sorry I didn't jump through all the hoops for proper branches for all this, but let me know if you want me to do it to get it submitted.

This original simple fix was left pending for 3+ months, and well, I wanted my 'master' branch back so I could keep going with my project. :)

**Comment by dwilt** [comment]
How can we get this merged in?

**Comment by mikelambert** [comment]
@davodesign84 , any concerns you have or want me to address?

**Comment by dwilt** [comment]
@mikelambert also, if you're feeling adventurous and giving.. cause I see you clearly know how to fix up this stuff in Android.. maybe you would take a stab at a fix for https://github.com/davodesign84/react-native-mixpanel/issues/56?

**Pull request merged**
