### PR TITLE
Implement new method to enable app session customization on iOS

### PR DESCRIPTION
**Pull request by andrejunges**
Related to https://github.com/davodesign84/react-native-mixpanel/issues/132

I don't have any experience with Objective C, so probably there are better ways to implement this functionality.
@davodesign84 it'd be great if you could take a look on it.

### CODE REVIEW

**Comment by andrejunges** [comment]
@davodesign84 any chance you get some time soon to take a look on this?

**Comment by louismullie** [comment]
@andrejunges Any pointers as to how this method should be called?

**Comment by trickeyd** [comment]
Yes is there any documentation for this? I am not at all hot on objective C I'm afraid.

**Comment by trickeyd** [comment]
Ah sorry - it is just in the docs for the js API. I thought this was something I had to call from within the obj c.

For anyone else that arrives here in a similar state of confusion:

iOS is from the JS:
`
// Allows control of the min/max sessions 
Mixpanel.setAppSessionPropertiesIOS({
  minimumSessionDuration: 20000,
  maximumSessionDuration: 90000,
});
`

Android is from the AndroidManifest.xml:
`
<meta-data android:name="com.mixpanel.android.MPConfig.MinimumSessionDuration"
    android:value="20000" />

<meta-data android:name="com.mixpanel.android.MPConfig.SessionTimeoutDuration"
    android:value="90000" />
`

**Pull request merged**
